import type { SkillNode, SkillTreeDefinition } from "@emberheir/sim";
import {
  CHAIN_LIGHTNING,
  EXECUTE,
  FIREBOLT,
  FLURRY,
  LACERATE,
  METEOR,
  POWER_STRIKE,
  REND,
  TOXIC_BURST,
  VENOM_COAT,
} from "./skills";

/**
 * Skill Tree (docs/design/skill-tree-v1.md): Core + Might + Arcana + Rupture, one Keystone per
 * branch. Coordinates are for the tree view: Core in the middle, Might up left, Arcana up right,
 * Rupture down left (Affliction will sit down right). Numbers are starting values.
 */

const CORE: readonly SkillNode[] = [
  {
    id: "core-heart",
    name: "Heir's Heart",
    branch: "core",
    kind: "minor",
    description: "+10 Life. Every Heir starts here.",
    links: ["core-vigor", "core-kindling", "core-spark", "core-footwork"],
    x: 0,
    y: 0,
    bonuses: { life: 10 },
  },
  {
    id: "core-vigor",
    name: "Vigor",
    branch: "core",
    kind: "minor",
    description: "+15 Life.",
    links: ["core-iron", "core-warding"],
    x: 0,
    y: 1,
    bonuses: { life: 15 },
  },
  {
    id: "core-iron",
    name: "Iron Hide",
    branch: "core",
    kind: "minor",
    description: "+10 Armor.",
    links: ["core-iron-will", "rupture-cruelty"],
    x: -0.9,
    y: 1.7,
    bonuses: { armor: 10 },
  },
  {
    id: "core-warding",
    name: "Warding",
    branch: "core",
    kind: "minor",
    description: "+5 % All Resistance.",
    links: ["core-iron-will"],
    x: 0.9,
    y: 1.7,
    bonuses: { allResistance: 0.05 },
  },
  {
    id: "core-iron-will",
    name: "Iron Will",
    branch: "core",
    kind: "notable",
    description: "+10 % Tenacity, +25 Life.",
    links: ["core-endurance", "core-resolve"],
    x: 0,
    y: 2.4,
    bonuses: { tenacity: 0.1, life: 25 },
  },
  {
    id: "core-footwork",
    name: "Footwork",
    branch: "core",
    kind: "minor",
    description: "+3 % Evasion.",
    links: ["core-alertness"],
    x: 0,
    y: -1.1,
    bonuses: { evasion: 0.03 },
  },
  {
    id: "core-kindling",
    name: "Kindling",
    branch: "core",
    kind: "minor",
    description: "+6 % Heat Gain.",
    links: ["might-strength"],
    x: -1,
    y: -0.6,
    bonuses: { heatGain: 0.06 },
  },
  {
    id: "core-spark",
    name: "First Spark",
    branch: "core",
    kind: "minor",
    description: "Start every fight with +8 Heat.",
    links: ["arcana-focus"],
    x: 1,
    y: -0.6,
    bonuses: { startingHeat: 8 },
  },
  {
    id: "core-endurance",
    name: "Endurance",
    branch: "core",
    kind: "minor",
    description: "+20 Life.",
    links: [],
    x: -0.8,
    y: 3.1,
    bonuses: { life: 20 },
  },
  {
    id: "core-resolve",
    name: "Resolve",
    branch: "core",
    kind: "minor",
    description: "+5 % Tenacity.",
    links: [],
    x: 0.8,
    y: 3.1,
    bonuses: { tenacity: 0.05 },
  },
  {
    id: "core-alertness",
    name: "Alertness",
    branch: "core",
    kind: "minor",
    description: "+3 % Evasion.",
    links: [],
    x: 0,
    y: -2,
    bonuses: { evasion: 0.03 },
  },
];

const MIGHT: readonly SkillNode[] = [
  {
    id: "might-strength",
    name: "Brawn",
    branch: "might",
    kind: "minor",
    description: "+6 % Physical Damage.",
    links: ["might-power-strike", "might-haste"],
    x: -1.8,
    y: -1.3,
    bonuses: { physicalDamage: 0.06 },
  },
  {
    id: "might-power-strike",
    name: "Power Strike",
    branch: "might",
    kind: "skill",
    description: "Unlocks Power Strike. Each rank adds a Skill Level.",
    links: ["might-brutal-force", "might-grit"],
    x: -2.8,
    y: -1.1,
    maxRanks: 3,
    skill: POWER_STRIKE,
  },
  {
    id: "might-haste",
    name: "Haste",
    branch: "might",
    kind: "minor",
    description: "+4 % Attack Speed.",
    links: ["might-brutal-force", "might-precision"],
    x: -2.1,
    y: -2.2,
    bonuses: { attackSpeed: 0.04 },
  },
  {
    id: "might-brutal-force",
    name: "Brutal Force",
    branch: "might",
    kind: "notable",
    description: "While wielding a Melee Weapon: +20 % Physical Damage, +10 Armor.",
    links: ["might-flurry"],
    x: -3.4,
    y: -2.1,
    weaponRange: "melee",
    bonuses: { physicalDamage: 0.2, armor: 10 },
  },
  {
    id: "might-precision",
    name: "Precision",
    branch: "might",
    kind: "minor",
    description: "+1 % Crit Chance.",
    links: ["might-killer-instinct"],
    x: -2.5,
    y: -3.1,
    bonuses: { critChance: 0.01 },
  },
  {
    id: "might-flurry",
    name: "Flurry",
    branch: "might",
    kind: "skill",
    description: "Unlocks Flurry. Each rank adds a Skill Level.",
    links: ["might-ferocity"],
    x: -4.4,
    y: -2.7,
    maxRanks: 3,
    skill: FLURRY,
  },
  {
    id: "might-killer-instinct",
    name: "Killer Instinct",
    branch: "might",
    kind: "notable",
    description: "+3 % Crit Chance, +5 % Trigger Chance.",
    links: ["might-swift-blades"],
    x: -3.2,
    y: -3.9,
    bonuses: { critChance: 0.03, triggerChance: 0.05 },
  },
  {
    id: "might-ferocity",
    name: "Ferocity",
    branch: "might",
    kind: "minor",
    description: "+8 % Physical Damage.",
    links: ["might-execute", "might-swift-blades", "might-whetstone"],
    x: -5,
    y: -3.6,
    bonuses: { physicalDamage: 0.08 },
  },
  {
    id: "might-swift-blades",
    name: "Swift Blades",
    branch: "might",
    kind: "minor",
    description: "+5 % Attack Speed.",
    links: ["might-execute"],
    x: -4.1,
    y: -4.5,
    bonuses: { attackSpeed: 0.05 },
  },
  {
    id: "might-execute",
    name: "Execute",
    branch: "might",
    kind: "skill",
    description: "Unlocks Execute. Each rank adds a Skill Level.",
    links: ["might-glass-focus"],
    x: -5.1,
    y: -4.9,
    maxRanks: 3,
    skill: EXECUTE,
  },
  {
    id: "might-glass-focus",
    name: "Glass Focus",
    branch: "might",
    kind: "keystone",
    description: "Heat no longer cools down. You take 20 % more damage.",
    links: [],
    x: -5.9,
    y: -5.8,
    keystone: { noHeatDecay: true, damageTaken: 0.2 },
  },
  {
    id: "might-grit",
    name: "Grit",
    branch: "might",
    kind: "minor",
    description: "+10 Armor.",
    links: [],
    x: -3.8,
    y: -0.6,
    bonuses: { armor: 10 },
  },
  {
    id: "might-whetstone",
    name: "Whetstone",
    branch: "might",
    kind: "minor",
    description: "+2 % Crit Chance.",
    links: [],
    x: -6,
    y: -3.3,
    bonuses: { critChance: 0.02 },
  },
];

/** Arcana mirrors Might on the right side. */
const ARCANA: readonly SkillNode[] = [
  {
    id: "arcana-focus",
    name: "Focus",
    branch: "arcana",
    kind: "minor",
    description: "+6 % Elemental Damage.",
    links: ["arcana-firebolt", "arcana-flow"],
    x: 1.8,
    y: -1.3,
    bonuses: { elementalDamage: 0.06 },
  },
  {
    id: "arcana-firebolt",
    name: "Firebolt",
    branch: "arcana",
    kind: "skill",
    description: "Unlocks Firebolt. Each rank adds a Skill Level.",
    links: ["arcana-kindled-mind", "arcana-insight"],
    x: 2.8,
    y: -1.1,
    maxRanks: 3,
    skill: FIREBOLT,
  },
  {
    id: "arcana-flow",
    name: "Flow",
    branch: "arcana",
    kind: "minor",
    description: "+5 % Heat Gain.",
    links: ["arcana-kindled-mind", "arcana-cinders"],
    x: 2.1,
    y: -2.2,
    bonuses: { heatGain: 0.05 },
  },
  {
    id: "arcana-kindled-mind",
    name: "Kindled Mind",
    branch: "arcana",
    kind: "notable",
    description: "While wielding a Ranged Weapon: +20 % Elemental Damage, +10 % Heat Gain.",
    links: ["arcana-chain-lightning"],
    x: 3.4,
    y: -2.1,
    weaponRange: "ranged",
    bonuses: { elementalDamage: 0.2, heatGain: 0.1 },
  },
  {
    id: "arcana-cinders",
    name: "Cinders",
    branch: "arcana",
    kind: "minor",
    description: "+5 % Chance to Burn.",
    links: ["arcana-storm-weaver"],
    x: 2.5,
    y: -3.1,
    bonuses: { burnChance: 0.05 },
  },
  {
    id: "arcana-chain-lightning",
    name: "Chain Lightning",
    branch: "arcana",
    kind: "skill",
    description: "Unlocks Chain Lightning. Each rank adds a Skill Level.",
    links: ["arcana-intensity"],
    x: 4.4,
    y: -2.7,
    maxRanks: 3,
    skill: CHAIN_LIGHTNING,
  },
  {
    id: "arcana-storm-weaver",
    name: "Storm Weaver",
    branch: "arcana",
    kind: "notable",
    description: "+8 % Chance to Shock, +5 % Elemental Penetration.",
    links: ["arcana-frost"],
    x: 3.2,
    y: -3.9,
    bonuses: { shockChance: 0.08, elementalPenetration: 0.05 },
  },
  {
    id: "arcana-intensity",
    name: "Intensity",
    branch: "arcana",
    kind: "minor",
    description: "+8 % Elemental Damage.",
    links: ["arcana-meteor", "arcana-frost", "arcana-attunement"],
    x: 5,
    y: -3.6,
    bonuses: { elementalDamage: 0.08 },
  },
  {
    id: "arcana-frost",
    name: "Frost",
    branch: "arcana",
    kind: "minor",
    description: "+5 % Chance to Chill.",
    links: ["arcana-meteor"],
    x: 4.1,
    y: -4.5,
    bonuses: { chillChance: 0.05 },
  },
  {
    id: "arcana-meteor",
    name: "Meteor",
    branch: "arcana",
    kind: "skill",
    description: "Unlocks Meteor. Each rank adds a Skill Level.",
    links: ["arcana-conduit"],
    x: 5.1,
    y: -4.9,
    maxRanks: 3,
    skill: METEOR,
  },
  {
    id: "arcana-conduit",
    name: "Arcane Conduit",
    branch: "arcana",
    kind: "keystone",
    description: "Skills cost 30 % less Heat. Your Default Attack deals 50 % less damage.",
    links: [],
    x: 5.9,
    y: -5.8,
    keystone: { skillCostMultiplier: 0.7, defaultAttackDamage: 0.5 },
  },
  {
    id: "arcana-insight",
    name: "Insight",
    branch: "arcana",
    kind: "minor",
    description: "+5 % All Resistance.",
    links: [],
    x: 3.8,
    y: -0.6,
    bonuses: { allResistance: 0.05 },
  },
  {
    id: "arcana-attunement",
    name: "Attunement",
    branch: "arcana",
    kind: "minor",
    description: "+6 % Elemental Damage.",
    links: [],
    x: 6,
    y: -3.3,
    bonuses: { elementalDamage: 0.06 },
  },
];

/** Rupture (Physical Over Time): down left, Bleed and Poison. */
const RUPTURE: readonly SkillNode[] = [
  {
    id: "rupture-cruelty",
    name: "Cruelty",
    branch: "rupture",
    kind: "minor",
    description: "+4 % Chance to Bleed.",
    links: ["rupture-lacerate", "rupture-venom"],
    x: -1.89,
    y: 2.02,
    bonuses: { bleedChance: 0.04 },
  },
  {
    id: "rupture-lacerate",
    name: "Lacerate",
    branch: "rupture",
    kind: "skill",
    description: "Unlocks Lacerate. Each rank adds a Skill Level.",
    links: ["rupture-butcher", "rupture-thick-blood"],
    x: -2.94,
    y: 1.9,
    maxRanks: 3,
    skill: LACERATE,
  },
  {
    id: "rupture-venom",
    name: "Venom",
    branch: "rupture",
    kind: "minor",
    description: "+5 % Chance to Poison.",
    links: ["rupture-butcher", "rupture-patience"],
    x: -2.21,
    y: 2.56,
    bonuses: { poisonChance: 0.05 },
  },
  {
    id: "rupture-butcher",
    name: "Butcher",
    branch: "rupture",
    kind: "notable",
    description: "While wielding a Melee Weapon: +10 % Chance to Bleed, +10 % Physical Damage.",
    links: ["rupture-venom-coat"],
    x: -3.57,
    y: 2.5,
    weaponRange: "melee",
    bonuses: { bleedChance: 0.1, physicalDamage: 0.1 },
  },
  {
    id: "rupture-patience",
    name: "Patience",
    branch: "rupture",
    kind: "minor",
    description: "+10 % Ailment Duration.",
    links: ["rupture-venomancer"],
    x: -2.62,
    y: 3.1,
    bonuses: { ailmentDuration: 0.1 },
  },
  {
    id: "rupture-venom-coat",
    name: "Venom Coat",
    branch: "rupture",
    kind: "skill",
    description: "Unlocks Venom Coat. Each rank adds a Skill Level.",
    links: ["rupture-sharpened"],
    x: -4.62,
    y: 2.86,
    maxRanks: 3,
    skill: VENOM_COAT,
  },
  {
    id: "rupture-venomancer",
    name: "Venomancer",
    branch: "rupture",
    kind: "notable",
    description: "+10 % Chance to Poison, +15 % Ailment Duration.",
    links: ["rupture-lingering"],
    x: -3.36,
    y: 3.58,
    bonuses: { poisonChance: 0.1, ailmentDuration: 0.15 },
  },
  {
    id: "rupture-sharpened",
    name: "Sharpened",
    branch: "rupture",
    kind: "minor",
    description: "+2 % Crit Chance.",
    links: ["rupture-rend", "rupture-lingering", "rupture-toxic-burst"],
    x: -5.25,
    y: 3.4,
    bonuses: { critChance: 0.02 },
  },
  {
    id: "rupture-lingering",
    name: "Lingering Wounds",
    branch: "rupture",
    kind: "minor",
    description: "+10 % Ailment Duration.",
    links: ["rupture-rend"],
    x: -4.3,
    y: 3.94,
    bonuses: { ailmentDuration: 0.1 },
  },
  {
    id: "rupture-rend",
    name: "Rend",
    branch: "rupture",
    kind: "skill",
    description: "Unlocks Rend. Each rank adds a Skill Level.",
    links: ["rupture-blood-price"],
    x: -5.35,
    y: 4.18,
    maxRanks: 3,
    skill: REND,
  },
  {
    id: "rupture-blood-price",
    name: "Blood Price",
    branch: "rupture",
    kind: "keystone",
    description: "Your Crits always Bleed. Your Crit Chance is halved.",
    links: [],
    x: -6.2,
    y: 4.72,
    keystone: { critsApplyBleed: true, critChanceMultiplier: 0.5 },
  },
  {
    id: "rupture-thick-blood",
    name: "Thick Blood",
    branch: "rupture",
    kind: "minor",
    description: "+5 % Tenacity.",
    links: [],
    x: -3.99,
    y: 1.6,
    bonuses: { tenacity: 0.05 },
  },
  {
    id: "rupture-toxic-burst",
    name: "Toxic Burst",
    branch: "rupture",
    kind: "skill",
    description: "Unlocks Toxic Burst. Each rank adds a Skill Level.",
    links: [],
    x: -6.3,
    y: 3.22,
    maxRanks: 3,
    skill: TOXIC_BURST,
  },
];

export const SKILL_TREE: SkillTreeDefinition = {
  nodes: [...CORE, ...MIGHT, ...ARCANA, ...RUPTURE],
  startNodeId: "core-heart",
};
