import type { IconName } from "../../ui/Icon";

/** Skill icons and slot tints (placeholder art). */
const SKILL_ICONS: Record<string, IconName> = {
  "power-strike": "strike",
  flurry: "flurry",
  execute: "execute",
  firebolt: "fire",
  "ice-lance": "snow",
  "chain-lightning": "bolt",
  meteor: "meteor",
  lacerate: "claw",
  "venom-coat": "venom",
  rend: "rend",
  "toxic-burst": "toxic",
  rake: "claw",
  "blight-spit": "venom",
  "rot-spray": "toxic",
  "moss-mend": "drop",
  devour: "drop",
  immolate: "flame",
  corrupt: "void",
  wither: "curse",
  "soul-harvest": "harvest",
  "heavy-swing": "slam",
  "quick-cuts": "flurry",
  "cinder-spit": "fire",
  "flame-dash": "flame",
  fireball: "fire",
  "obsidian-shell": "shell",
  eruption: "meteor",
  pounce: "wolf",
  "ice-bolt": "snow",
  "glacial-mend": "drop",
  avalanche: "slam",
  "void-bolt": "void",
  "arc-dash": "bolt",
  "forked-bolt": "bolt",
  thunderclap: "bolt",
  "void-lance": "void",
  hex: "curse",
  consume: "void",
  "rift-snap": "slam",
  "soul-reap": "harvest",
  "harvest-swing": "harvest",
  ashfall: "meteor",
  "last-harvest": "harvest",
  feint: "strike",
  "piercing-shot": "bow",
  cleave: "axe",
  "plague-cloud": "toxic",
  thunderstrike: "bolt",
  "frost-nova": "snow",
  inferno: "flame",
  "void-rift": "void",
  "iron-bastion": "shield",
  rally: "cycle",
  "skull-crack": "slam",
  "barbed-arrow": "bow",
  "heavy-bolt": "crossbow",
  "crushing-blow": "hammer",
  "serrated-edge": "claw",
  envenom: "venom",
};

export function skillIcon(skillId: string): IconName {
  return SKILL_ICONS[skillId] ?? (skillId.includes("slam") ? "slam" : "strike");
}

const SKILL_TINTS: Record<string, string> = {
  "power-strike": "#8a6a4a",
  flurry: "#7a5a24",
  execute: "#6a2a20",
  firebolt: "#a8401a",
  "ice-lance": "#2d6a8a",
  "chain-lightning": "#8a7a20",
  meteor: "#a8401a",
  lacerate: "#8a1f2c",
  "venom-coat": "#4f6a12",
  rend: "#6a1420",
  "toxic-burst": "#5f7a0e",
  immolate: "#a8401a",
  corrupt: "#5a2a8a",
  wither: "#4a1f6a",
  "soul-harvest": "#6a2a8a",
  "void-bolt": "#5a2a8a",
  feint: "#7a6a4a",
  "piercing-shot": "#5a6a3a",
  cleave: "#7a1a24",
  "plague-cloud": "#4f6a12",
  thunderstrike: "#8a7a20",
  "frost-nova": "#2d6a8a",
  inferno: "#b8481a",
  "void-rift": "#4a1f7a",
  "iron-bastion": "#5a5a6a",
  rally: "#8a5a1a",
  "skull-crack": "#7a6a3a",
  "barbed-arrow": "#7a2a2c",
  "heavy-bolt": "#5a5a6a",
  "crushing-blow": "#5e5750",
  "serrated-edge": "#8a1f2c",
  envenom: "#4f6a12",
};

export function skillTint(skillId: string): string {
  return SKILL_TINTS[skillId] ?? "#6b5a3e";
}
